apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hn997yjkn-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bcaad7d93e.pysq.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:a186b871af282f16719e904bd10f1601b3dbeeb9@sha256:06fae15effd33a1a810c5269a47174ca231c89a6119bfa157364b2bfc64fbcbe
          name: container-image
